= CreateProjects

This is a fairly crude Eclipse plug-in that will create the Eclipse metadata
for the course projects, initially for
https://learningtree.com/936/[my Java Enterprise course],
and commonly for use after my other project
https://github.com/IanDarwin/makehandsons[makehandsons] has been run.

== HowTo

Open the project in Eclipse.

Edit the list of projects to suit your course list of projects,
in `ProjectsList.java` (this will eventually move out of the code
into a file or GUI).

Make sure you are in the workspace where you want to create projects
(Use `File->Switch Workspace` if needed).

If you want to test it standalone, right-click on the project and do
`RunAs->Eclipse Application`.

For now it's easiest to Export the project as a Plug-in into your main workspace.
Just do `File->Export->PlugIn Development->Deployable Plugins and Fragments`.
Click next. Select the `CreateProjects` plugin
and select the strangely-named `Install into host. Repository:` 
(it should have filled in the Repository with a subdirectory of the current workspace;
do not change this).
Click `Finish`. Accept the "unsigned" warning (if you trust me, mwah ha ha).
Accept the `Restart now` choice if offered; you can only do this export once
without restarting, so might as well accept it now.

Open `Window->Show View->Other`, `Course Maintenance`, `Create Projects View`.

Click the big button at the bottom that says `Create`.

Kick back and watch your projects appear out of the ether!
Note that this can take up to 5-10 minutes, so be patient.
First time I ran it, I was just about to send a `kill` signal after 5 mins,
when "to my wondering eyes", it finished.

Now give Eclipse a few more mins to build all the projects, and maybe do some
maven fetching as well.

== TODO

Fixup minor validation problem (for now just click `Continue`).

Have the code check that project has Java Nature, Maven Nature, etc.

Make a more realistic UI. It could show the list of projects with checkboxes
and color coded status (created, has JavaNature, has MavenNature, etc.)

Read the list of projects from a file.  You might ask: why not just read the
directory of the workspace? Because the next TODO is to support projects at
external file locations with a 2nd argument in the file, e.g.,

	ex31
	ex31solution
	javasrc		C:/javasrc
	jpademo		C:/jpademo

Maybe a ProgressMonitor for project creation.

== See Also

A great resource for Eclipse Plugin Development is
Lars Vogel's http://vogella.com[vogella.com].
Lars offers both free online tutorials and in-class instruction (in Europe).
