= CreateProjects

This is a fairly crude Eclipse plug-in that will create the Eclipse metadata
for the course projects, initially for
https://learningtree.com/936/[my Java Enterprise course],
and commonly for use after my other project
https://github.com/IanDarwin/makehandsons[makehandsons] has been run.

== HowTo

Open the `CreateProjects` project in Eclipse:

* Either open it using the GIT plugin to clone and create at the same time
* Or, git clone manually, and do `File->New->Java Project`, and just type
`CreateProjects` in the `Project Name` field. When asked to create a `module-info`,
click `Don't Create`.  If asked to `Open the Java perspective`, do so.

This is a DIY Eclipse Plugin, so you need the _e4_ tools. 
Not all Eclipse downloads include these.
If you get a bunch of undefineds,
you need to install _e4_. Go to `Help->Install New Software`, select 
_Latest Release_ - `https://download.eclipse.releases/latest`, and pick
`Eclipse e4 Tools Developer Resources.` (If it's already selected, that's
not your problem). Click `Next` then `Finish`.
In a minute or two you will be prompted to restart, which you must do
if you just installed software.

Make sure you are in the workspace where you want to create projects
(Use `File->Switch Workspace` if needed).

Create or edit the list of projects to suit your course list of projects,
in `projectlist.java` _in the root of the workspace_
(this will someday^Wsomedecade move out of the code into a GUI).

The input is a list of projects, one per line. An optional
second field for projects outside the workspace contains the absolute path 
but excluding the leading "C:" (on Windows it goes in C:/whatever whereas in Unix/Linux
it goes in ~/whatever).

Sample input:

	ex21
	ex21solution
	javasrc git/javasrc

On Windows the `javasrc` project would be in C:\git\javasrc; on Unix/Linux it would
be in ~/git/javasrc.

If you want to test the program standalone, right-click on the project and do
`RunAs->Eclipse Application`.

For now it's easiest to Export the project as a Plug-in into your main workspace.
Just do `File->Export... PlugIn Development->Deployable Plugins and Fragments`.
Click next. Select the `CreateProjects` plugin.
Near the bottom of the dialog,
select the strangely-named `Install into host. Repository:` 
(it should have filled in the Repository with a subdirectory of the current workspace;
do not change this).
Click `Finish`. Accept the "unsigned" warning (if you trust me, mwah ha ha).
Accept the `Restart now` choice if offered; you can only do this export once
without restarting, so might as well accept it now.

Open `Window->Show View->Other`, `Course Maintenance`, `Create Projects View`.

Click the big button at the bottom that says `Create`.

Kick back and watch your projects appear out of the ether!
Note that *this can take up to 5-10 minutes, so be patient*.
First time I ran it, I was just about to send a `kill` signal after 5 mins,
when "to my wondering eyes", it finished.

Now give Eclipse a few more mins to build all the projects (and it may do some
Maven fetching as well).

== TODO

Fixup minor validation problem (for now just click `Continue`).

Have the code check that project has Java Nature, Maven Nature, etc.

Make a more realistic UI. It could:
* show the list of all folders/projects with checkboxes.
* use color coded status for them (created, has JavaNature, has MavenNature, etc.).
* Allow setting the absPath prefixed  (what now defaults to C: or ~).
* Maybe a ProgressMonitor during project creation.

Get the unit test working?

== See Also

A great resource for Eclipse Plugin Development is
Lars Vogel's http://vogella.com[vogella.com].
Lars offers both free online tutorials and in-class instruction (in Europe).
